spring.application.name=urlShortener

spring.datasource.url={DATABASE_URL}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.swagger-ui.path=/swagger
springdoc.api-docs.enabled=true